# Generated by Django 5.2.5 on 2025-08-11 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('developers', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Developer'}, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'groups__name': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_projects', 'Can create projects'), ('cannot_create_projects', 'Can not create projects'), ('can_assign_developers', 'Can assign developers')],
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('bug_type', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('resolved', 'Resolved'), ('completed', 'Completed')], default='new', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bug_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Developer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(limit_choices_to={'groups__name': 'QA'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_bugs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='bugzilla.project')),
            ],
            options={
                'permissions': [('can_report_bugs', 'Can report bugs'), ('are_assigned_bugs', 'Are Assigned Bugs')],
                'unique_together': {('project', 'title')},
            },
        ),
    ]
